Modify the kernel configuration
./mer_verify_kernel_config ~/halium-9.0/kernel/oneplus/msm8994/arch/arm64/configs/oneplus2_defconfig



WARNING: CONFIG_CGROUP_MEM_RES_CTLR is invalid
It is unset
Allowed values : y, !, <=3.5
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html, only valid if kernel version <= 3.5

ERROR: CONFIG_TMPFS_POSIX_ACL is invalid
It is unset
Allowed values : y
Comment says: systemd: required by hybris-boot init-script, if you want pam_systemd.so to setup your "seats". http://cgit.freedesktop.org/systemd/systemd/commit/README?id=77b6e19458f37cfde127ec6aa9494c0ac45ad890

WARNING: CONFIG_NFS_COMMON is invalid
It is unset
Allowed values : y, !
Comment says: optional, for NFS support

ERROR: CONFIG_QUOTA is invalid
It is unset
Allowed values : y
Comment says: Quota is needed to prevent additional users from taking all space

ERROR: CONFIG_UTS_NS is invalid
It is unset
Allowed values : y
Comment says: Namespacing option needed by firejail

WARNING: CONFIG_CGROUP_MEM_RES_CTLR_KMEM is invalid
It is unset
Allowed values : y, !, <=3.5
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html, only valid if kernel version <= 3.5

ERROR: CONFIG_QUOTA_NETLINK_INTERFACE is invalid
It is unset
Allowed values : y
Comment says: For quota_nld service

WARNING: CONFIG_NETFILTER_XT_MATCH_SCTP is invalid
It is unset
Allowed values : y, m, !
Comment says: connman: for iptables sctp match

WARNING: CONFIG_NFS_V3 is invalid
It is unset
Allowed values : y, !
Comment says: optional, for NFS support

WARNING: CONFIG_NETPRIO_CGROUP is invalid
It is unset
Allowed values : y, !
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html

WARNING: CONFIG_UDF_FS is invalid
It is unset
Allowed values : y, m, !
Comment says: optional extra filesystem (DVD & portable USB)

WARNING: CONFIG_SECURITY_YAMA_STACKED is invalid
It is unset
Allowed values : y, !, <4.3
Comment says: optional, only valid for kernel < 4.3

WARNING: CONFIG_LOCKD_V4 is invalid
It is unset
Allowed values : y, !
Comment says: optional, for NFS support

WARNING: CONFIG_BTRFS_FS is invalid
It is unset
Allowed values : y, !
Comment says: optional extra filesystem (BTRFS)

ERROR: CONFIG_FHANDLE is invalid
It is unset
Allowed values : y
Comment says: systemd: http://cgit.freedesktop.org/systemd/systemd/commit/README?id=001809282918f273d372f1ee09d10b783c18a474

WARNING: CONFIG_LBDAF is invalid
It is unset
Allowed values : y, !
Comment says: ext4 filesystem requires this in order to support filesysetms with huge_file feature, which is enabled by default by mke2fs.ext4

WARNING: CONFIG_IP6_NF_MATCH_FRAG is invalid
It is unset
Allowed values : y, m, !
Comment says: connman: for ip6tables frag match

ERROR: CONFIG_QFMT_V2 is invalid
It is unset
Allowed values : y
Comment says: Use this version of the interface for quotactl

WARNING: CONFIG_CGROUP_MEM_RES_CTLR_SWAP is invalid
It is unset
Allowed values : y, !, <=3.5
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html, only valid if kernel version <= 3.5

ERROR: CONFIG_VT is invalid
It is unset
Allowed values : y
Comment says: Required for virtual consoles

ERROR: CONFIG_IKCONFIG_PROC is invalid
It is unset
Allowed values : y
Comment says: Required by hybris-boot init-script

WARNING: CONFIG_ISO9660_FS is invalid
It is unset
Allowed values : y, m, !
Comment says: optional extra filesystem (CD-ROM)

WARNING: CONFIG_CHECKPOINT_RESTORE is invalid
It is unset
Allowed values : y, !
Comment says: rich-core-dumper (https://github.com/mer-tools/sp-rich-core/) needs this to collect all data for environment recreation.

WARNING: CONFIG_MODULES is invalid
It is unset
Allowed values : y, !
Comment says: optional, required for module support (Such as WLAN for example)

WARNING: CONFIG_BLK_DEV_NBD is invalid
It is unset
Allowed values : y, m, !
Comment says: optional, for NFS & CIFS support

WARNING: CONFIG_NFS_FS is invalid
It is unset
Allowed values : y, m, !
Comment says: optional, for NFS support

WARNING: CONFIG_NFS_V4 is invalid
It is unset
Allowed values : y, !
Comment says: optional, for NFS support

WARNING: CONFIG_AUTOFS4_FS is invalid
It is unset
Allowed values : y, m, !
Comment says: systemd (optional): http://cgit.freedesktop.org/systemd/systemd/commit/README?id=713bc0cfa477ca1df8769041cb3dbc83c10eace2

WARNING: CONFIG_IP6_NF_MATCH_AH is invalid
It is unset
Allowed values : y, m, !
Comment says: connman: for ip6tables ah match

ERROR: CONFIG_IPC_NS is invalid
It is unset
Allowed values : y
Comment says: Namespacing option needed by firejail

ERROR: CONFIG_DUMMY is invalid
Value is: y
Allowed values : n
Comment says: 

WARNING: CONFIG_FANOTIFY is invalid
It is unset
Allowed values : y, !
Comment says: optional, required for systemd readahead.

WARNING: CONFIG_NETFILTER_XT_MATCH_NFACCT is invalid
It is unset
Allowed values : y, m, !
Comment says: connman (optional): for routing and statistic support in sessions, http://git.kernel.org/cgit/network/connman/connman.git/commit/README?id=41f37125887cb9208da2441e350e1e3324c17ee6

WARNING: CONFIG_TMPFS_XATTR is invalid
It is unset
Allowed values : y, !
Comment says: systemd (optional): strongly recommended, http://cgit.freedesktop.org/systemd/systemd/commit/README?id=713bc0cfa477ca1df8769041cb3dbc83c10eace2

WARNING: CONFIG_SUNRPC_GSS is invalid
It is unset
Allowed values : y, m, !
Comment says: optional, for NFS support

WARNING: CONFIG_BLK_CGROUP is invalid
It is unset
Allowed values : y, !
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html

WARNING: CONFIG_NF_NAT_IPV6 is invalid
It is unset
Allowed values : y, m, !
Comment says: connman: to enable IPv6 NAT

WARNING: CONFIG_SECURITY_YAMA is invalid
It is unset
Allowed values : y, !
Comment says: optional, prevents user's processes from ptracing each other

WARNING: CONFIG_NFS_ACL_SUPPORT is invalid
It is unset
Allowed values : y, m, !
Comment says: optional, for NFS support

WARNING: CONFIG_AUDIT is invalid
Value is: y
Allowed values : n, !
Comment says: This will disable SELinux! That's ok, because hybris adaptations must not have SELinux, but if your device needs its support in kernel, set AUDIT=y and SELINUX_BOOTPARAM=y. Then disable them via kernel cmdline: audit=0 selinux=0. You can also leave audit enabled, if you don't plan to use systemd's containers: http://cgit.freedesktop.org/systemd/systemd/commit/README?id=77b6e19458f37cfde127ec6aa9494c0ac45ad890

WARNING: CONFIG_NET_CLS_CGROUP is invalid
It is unset
Allowed values : y, !
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html

WARNING: CONFIG_CGROUP_DEVICE is invalid
It is unset
Allowed values : y, !
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html

ERROR: CONFIG_PID_NS is invalid
It is unset
Allowed values : y
Comment says: Namespacing option needed by firejail

WARNING: CONFIG_NFS_USE_KERNEL_DNS is invalid
It is unset
Allowed values : y, !
Comment says: optional, for NFS support

WARNING: CONFIG_RTC_DRV_CMOS is invalid
It is unset
Allowed values : y, !
Comment says: optional, but highly recommended

WARNING: CONFIG_BT_HCIUART is invalid
It is unset
Allowed values : y, !
Comment says: Bluez (optional): Needed if bluez used as bluetooth stack

WARNING: CONFIG_CIFS is invalid
It is unset
Allowed values : y, m, !
Comment says: optional extra filesystem (CIFS - Windows net fs)

WARNING: CONFIG_NFS_V4_1 is invalid
It is unset
Allowed values : y, !
Comment says: optional, for NFS support

WARNING: CONFIG_SUNRPC is invalid
It is unset
Allowed values : y, m, !
Comment says: optional, for NFS support

WARNING: CONFIG_BT_HCIUART_H4 is invalid
It is unset
Allowed values : y, !
Comment says: Bluez (optional): Needed if bluez used as bluetooth stack

WARNING: CONFIG_NETFILTER_XT_MATCH_RECENT is invalid
It is unset
Allowed values : y, m, !
Comment says: connman: for iptables recent match

WARNING: CONFIG_WATCHDOG_NOWAYOUT is invalid
It is unset
Allowed values : y, !
Comment says: If device uses watchdogs with dsme (https://github.com/nemomobile/dsme), this option should be enabled or watchdog does not protect the device in case dsme crashes.

WARNING: CONFIG_IP6_NF_MATCH_MH is invalid
It is unset
Allowed values : y, m, !
Comment says: connman: for ip6tables mh match

WARNING: CONFIG_CGROUP_PERF is invalid
It is unset
Allowed values : y, !
Comment says: systemd (optional): http://0pointer.de/blog/projects/cgroups-vs-cgroups.html

WARNING: CONFIG_LOCKD is invalid
It is unset
Allowed values : y, m, !
Comment says: optional, for NFS support

ERROR: CONFIG_DEVTMPFS_MOUNT is invalid
It is unset
Allowed values : y
Comment says: Required by hybris-boot init-script

WARNING: CONFIG_SECURITY_SELINUX_BOOTPARAM is invalid
It is unset
Allowed values : y, !
Comment says: Required by hybris, SELinux needs to be disabled. Leave as not set, if you have unset AUDIT (read more about the CONFIG_AUDIT flag)

WARNING: CONFIG_HIDRAW is invalid
It is unset
Allowed values : y, m, !
Comment says: optional: Support HID devices

WARNING: CONFIG_NETFILTER_XT_MATCH_DCCP is invalid
It is unset
Allowed values : y, m, !
Comment says: connman: for iptables dccp match

WARNING: CONFIG_ECRYPT_FS is invalid
It is unset
Allowed values : y, m, !
Comment says: optional extra filesystem (ecryptfs)

WARNING: CONFIG_NFS_V3_ACL is invalid
It is unset
Allowed values : y, !
Comment says: optional, for NFS support

WARNING: CONFIG_NETFILTER_NETLINK_ACCT is invalid
It is unset
Allowed values : y, m, !
Comment says: connman (optional): for routing and statistic support in sessions, http://git.kernel.org/cgit/network/connman/connman.git/commit/README?id=41f37125887cb9208da2441e350e1e3324c17ee6

ERROR: CONFIG_QUOTACTL is invalid
It is unset
Allowed values : y
Comment says: To adjust quota

ERROR: CONFIG_DEVTMPFS is invalid
It is unset
Allowed values : y
Comment says: systemd: http://cgit.freedesktop.org/systemd/systemd/commit/README?id=713bc0cfa477ca1df8769041cb3dbc83c10eace2

WARNING: CONFIG_FW_LOADER_USER_HELPER is invalid
Value is: y
Allowed values : n, !
Comment says: it's actually needed by some Lollipop based devices; systemd(optional): http://cgit.freedesktop.org/systemd/systemd/commit/README?id=713bc0cfa477ca1df8769041cb3dbc83c10eace2